-- Custom indexes, triggers, and CHECK constraints not auto-generated by Drizzle Kit

-- Partial Indexes
CREATE INDEX IF NOT EXISTS idx_categories_user_jd ON interview_categories(user_id, jd_id, display_order) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_user_slug_unique ON interview_categories(user_id, slug) WHERE jd_id IS NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_jd_name_unique ON interview_categories(user_id, jd_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_source_jd ON interview_categories(source_category_id, jd_id) WHERE source_category_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_questions_category_order ON interview_questions(category_id, display_order) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_questions_user_jd ON interview_questions(user_id, jd_id, category_id, display_order) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_questions_origin_jd ON interview_questions(origin_question_id, jd_id) WHERE origin_question_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_questions_keywords_gin ON interview_questions USING GIN(keywords);
CREATE INDEX IF NOT EXISTS idx_followups_question_order ON followup_questions(question_id, display_order) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_jobs_user_status ON job_descriptions(user_id, status, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_questions_deleted ON interview_questions(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_categories_deleted ON interview_categories(deleted_at) WHERE deleted_at IS NOT NULL;

-- updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at auto-update
CREATE TRIGGER trg_jobs_updated_at BEFORE UPDATE ON job_descriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_categories_updated_at BEFORE UPDATE ON interview_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_questions_updated_at BEFORE UPDATE ON interview_questions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_followups_updated_at BEFORE UPDATE ON followup_questions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- CHECK constraints
ALTER TABLE interview_categories ADD CONSTRAINT chk_categories_system_no_jd CHECK (user_id != 'system' OR jd_id IS NULL);
ALTER TABLE interview_questions ADD CONSTRAINT chk_questions_system_no_jd CHECK (user_id != 'system' OR jd_id IS NULL);
